// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 IONOS SE
// Author: Roman Penyaev <r.peniaev@gmail.com>

// Re-export the generated code so client/server can use "common::snpguard::..."
pub mod snpguard {
    // Include protobuf messages generated by prost (no gRPC services)
    tonic::include_proto!("snpguard");

    // Export message types for REST/HTTPS endpoints
    pub use prost::Message;
}
